# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PULLREQUEST_TO_MASTER

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.version }}'
          distribution: 'adopt'
          cache: maven      
      - name: enable automerge    
        uses: hmarr/auto-approve-action@v2
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         pull-request-number: ${{ github.event.inputs.pullRequestNumber }} 
         
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P java${{ matrix.version }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUBKEY }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=MOderkerk_EmailValidationService -Dsonar.qualitygate.wait=true
      - name: set automerge to true
        uses: christianvuerings/add-labels@v1
        with:
          labels: |
            auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUBKEY }}
      - name: Approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Integration check
          uses: squalrus/merge-bot@v0.1.0
          with:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUBKEY }}
            test: false
            reviewers: FALSE
            labels: auto-merge, automated-pr
            blocking_labels: do not merge
            checks_enabled: true
            method: MERGE
            delete_source_branch: false
