# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RELEASEv2

on:
  pull_request:
    types:
      - closed

    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Give the Branch name"
        required: true
        default: "master"
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 11 ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.version }}'
          distribution: 'adopt'
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Change Version of Release version
        run: mvn -B versions:set -DnewVersion=1.0.${{github.run_number}} --file pom.xml -P java${{ matrix.version }}
      
      - name: Create Release Notes
        uses: johnyherangi/create-release-notes@main
        id: create-release-notes
        env:
           GITHUB_TOKEN:  ${{ secrets.DEPLOYMENT }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
             GITHUB_TOKEN:  ${{ secrets.DEPLOYMENT }}
        with:
          tag_name: 1.0.${{github.run_number}}
          release_name: Release 1.0.${{github.run_number}}
          body: ${{ steps.create-release-notes.outputs.release-notes }}
      
    
      - name: Publish to GitHub Packages Apache Maven
        run: mvn clean deploy -DuniqueVersion=true -Dmaven.source.useDefaultManifestFile=true -DdeplyAtEnd=true -DskipTests=true -Dmaven.source.includePom=true -Dmaven.install.skip=true --file pom.xml -P java${{ matrix.version }} 
        
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT }}
